### PR TITLE
code added for #134

### PR DESCRIPTION
**Pull request by 4shutosh**
for issuse https://github.com/aayush26/leetcode/issues/21

### CODE REVIEW

**Comment by aayush26** [comment]
Can you add runtime and memory usage beats % post submission in leetcode as part of comment just below the problem link in your code?

Read more on guidelines on how to contribute:
https://github.com/aayush26/leetcode#how-to-contribute

**Comment by aayush26** [comment]
please fix the folder structure. it should be:     
`#134/java/Solution.java`

**Comment by 4shutosh** [comment]
Fixed directory sir!
Please check now. Sorry for inconvenience

**Comment by aayush26** [comment]
nit: Can you also add the runtime and memory usage as mentioned in the contribution guidelines?

Rest all LGTM.

**Comment by 4shutosh** [comment]
Done Sir!

**Pull request merged**
